export const quotes = [
  "The man who does not read books has no advantage over the one who cannot read them.",
  "Education is the passport to the future, for tomorrow belongs to those who prepare for it today",
  "Teachers can open the door, but you must enter it yourself.",
  "The beautiful thing about learning is that no one can take it away from you.",
  "Education is the most powerful weapon you can use to change the world",
  "The mind is not a vessel to be filled but a fire to be ignited.",
  "Don,t let what you cannot do interfere with what you can do.",
  "A person who never made a mistake never tried anything new.",
  "Never let the fear of striking out stop you from playing the game.",
  "You don,t have to be great to start, but you have to start to be great.",
  "The expert in anything was once a beginner.",
  "The way to get started is to quit talking and begin doing.",
  "There are no shortcuts to any place worth going.",
  "I think it,s possible for ordinary people to choose to be extraordinary.",
  "I find that the harder I work, the more luck I seem to have.",
  "Genius is 10% inspiration, 90% perspiration.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "Success is the sum of small efforts, repeated.",
];
